# this need to be apply first before installing certificates for any url
# =====================================================================
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http-01-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: pod3ch4dev@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-cluster-issuer
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
